services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - SECRET_KEY=supersecretkey
      - PORT=${PORT}
      - ADMIN_SUBNET=${ADMIN_SUBNET}
      - MERAKI_API_ENABLED=${MERAKI_API_ENABLED}
      - MERAKI_API_KEY=${MERAKI_API_KEY}
      - MERAKI_ORG_ID=${MERAKI_ORG_ID}
      - MERAKI_SSID_NAMES=${MERAKI_SSID_NAMES}
      - LAN_IP=${LAN_IP}
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase

volumes:
  postgres_data:
